version: '3.8'
services:
  movies:
    image: shivakumar700/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: shivakumar700/dth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: shivakumar700/train:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: shivakumar700/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
